version: '3.8'

services:
  web:
    build: ./
    container_name: itfoxnewsproject
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/itfoxnewsproject
    ports:
      - 8000:8000
    env_file:
      - ./itfoxnews/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: itfoxnewsdb
    volumes:
      - audio_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./itfoxnews/.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: sound_cloud_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  audio_library_postgres_data: