version: '3.8'

services:
  web:
    build: ./
    container_name: itfoxnewsproject
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./itfoxnews/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: itfoxnewsdb
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./itfoxnews/.env
    ports:
      - 5432:5432

volumes:
  pgdata: